childBlocks: ''
field: 36c0a2a3-459b-4683-9aa6-b0a9d4f70494 # Page Content
fieldLayouts:
  46e26c25-fe5d-4f85-868c-00a4116e4cfe:
    tabs:
      -
        elements:
          -
            fieldUid: 7417909e-cf8b-4528-8a4a-05536140e428 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 79c7b342-e5c4-4bb9-bf05-a8d17fffe884 # Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 2
handle: c_button
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Button
sortOrder: 22
topLevel: false
