childBlocks: ''
field: 36c0a2a3-459b-4683-9aa6-b0a9d4f70494 # Page Content
fieldLayouts:
  c123a578-eeca-46fa-9c07-715053a75a25:
    tabs:
      -
        elements:
          -
            fieldUid: d6055877-27dd-431d-b5ea-a58c66494c48 # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b56d8dc7-a81a-4d45-b918-ddacc1675bcc # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7417909e-cf8b-4528-8a4a-05536140e428 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 79c7b342-e5c4-4bb9-bf05-a8d17fffe884 # Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 2
handle: c_simple_block
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Simple Block'
sortOrder: 19
topLevel: false
