childBlocks: ''
field: 36c0a2a3-459b-4683-9aa6-b0a9d4f70494 # Page Content
fieldLayouts:
  356b270f-3222-47eb-8dc7-03677fa3ae70:
    tabs:
      -
        elements:
          -
            fieldUid: aab8002b-446b-41d5-a1c0-e5f01e6eda00 # Plain Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b56d8dc7-a81a-4d45-b918-ddacc1675bcc # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7417909e-cf8b-4528-8a4a-05536140e428 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: c_tab_dropdown
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Tab - Dropdown'
sortOrder: 8
topLevel: false
