childBlocks: ''
field: 36c0a2a3-459b-4683-9aa6-b0a9d4f70494 # Page Content
fieldLayouts:
  f0a98658-82a3-45eb-8b1a-be7c8841cf1b:
    tabs:
      -
        elements:
          -
            fieldUid: aab8002b-446b-41d5-a1c0-e5f01e6eda00 # Plain Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0b2c2e4a-eb80-4374-8c6b-0bf9a050ed8f # Stat
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: c_tab
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Tab
sortOrder: 7
topLevel: false
