childBlocks: null
field: 36c0a2a3-459b-4683-9aa6-b0a9d4f70494 # Page Content
fieldLayouts:
  418adee6-9a25-448a-bad9-17ac5db6ef9d:
    tabs:
      -
        elements:
          -
            fieldUid: 31f2b9a6-e84e-4ec9-8152-08f4a6b90441 # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d6055877-27dd-431d-b5ea-a58c66494c48 # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 47b7e378-7822-4a43-b757-c1e4b1de2996 # ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 023efee0-7481-4a62-b79d-b48cad1ca37b # Height
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 2
handle: m_banner_hero
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Banner
sortOrder: 3
topLevel: true
