childBlocks:
  - m_card_background
field: 36c0a2a3-459b-4683-9aa6-b0a9d4f70494 # Page Content
fieldLayouts:
  c147b7d6-5473-493a-8c55-8e1b3865cb66:
    tabs:
      -
        elements:
          -
            fieldUid: 54c7446b-ba5e-4499-85f6-9e661a1087f1 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 47b7e378-7822-4a43-b757-c1e4b1de2996 # ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 69849cd6-effc-4de9-b732-74455851ac89 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 2
handle: m_cards_background
maxBlocks: 0
maxChildBlocks: 4
maxSiblingBlocks: 0
name: 'Cards - Background'
sortOrder: 10
topLevel: true
