childBlocks:
  - m_card_basic
  - m_card_links
field: 36c0a2a3-459b-4683-9aa6-b0a9d4f70494 # Page Content
fieldLayouts:
  a191ed88-bd44-4520-9b7e-72c58bccde81:
    tabs:
      -
        elements:
          -
            fieldUid: 47b7e378-7822-4a43-b757-c1e4b1de2996 # ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 69849cd6-effc-4de9-b732-74455851ac89 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: m_cards_basic
maxBlocks: 0
maxChildBlocks: 3
maxSiblingBlocks: 0
name: 'Cards - Basic'
sortOrder: 12
topLevel: true
