childBlocks: ''
field: 36c0a2a3-459b-4683-9aa6-b0a9d4f70494 # Page Content
fieldLayouts:
  fbf4ce9c-7120-49a2-9bc3-4f8f9779db0d:
    tabs:
      -
        elements:
          -
            fieldUid: 54c7446b-ba5e-4499-85f6-9e661a1087f1 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d6055877-27dd-431d-b5ea-a58c66494c48 # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b56d8dc7-a81a-4d45-b918-ddacc1675bcc # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7417909e-cf8b-4528-8a4a-05536140e428 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 69849cd6-effc-4de9-b732-74455851ac89 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 2
handle: m_card_basic
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Card - Basic'
sortOrder: 13
topLevel: false
