childBlocks: ''
field: 36c0a2a3-459b-4683-9aa6-b0a9d4f70494 # Page Content
fieldLayouts:
  ddf406ac-8919-4ea4-9e90-82196b3a2de1:
    tabs:
      -
        elements:
          -
            fieldUid: 0b2c2e4a-eb80-4374-8c6b-0bf9a050ed8f # Stat
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: aab8002b-446b-41d5-a1c0-e5f01e6eda00 # Plain Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Card
        sortOrder: 1
handle: m_card_background
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Card - Background'
sortOrder: 11
topLevel: false
