childBlocks: ''
field: 36c0a2a3-459b-4683-9aa6-b0a9d4f70494 # Page Content
fieldLayouts:
  6e7e99d0-ecbc-4bed-ba9a-82cbe85aa66c:
    tabs:
      -
        elements:
          -
            fieldUid: d6055877-27dd-431d-b5ea-a58c66494c48 # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 479bed28-3864-4839-9a44-fae94296daf3 # Phone Number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eb9ddbe8-59e8-4a76-898e-9f77608f8f28 # Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4aa2987a-64ab-4605-adec-de3d6e984f60 # Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: m_owners_form
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Owners Form'
sortOrder: 27
topLevel: true
