childBlocks:
  - c_tab
  - c_tab_dropdown
field: 36c0a2a3-459b-4683-9aa6-b0a9d4f70494 # Page Content
fieldLayouts:
  90f2bf45-1ec8-4162-b1e8-845e27b61ff3:
    tabs:
      -
        elements:
          -
            fieldUid: d6055877-27dd-431d-b5ea-a58c66494c48 # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 54c7446b-ba5e-4499-85f6-9e661a1087f1 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: m_tabs
maxBlocks: 0
maxChildBlocks: 8
maxSiblingBlocks: 0
name: Tabs
sortOrder: 5
topLevel: true
