childBlocks: null
field: 36c0a2a3-459b-4683-9aa6-b0a9d4f70494 # Page Content
fieldLayouts:
  85dfb084-2037-4177-be5a-8c0ba361cef9:
    tabs:
      -
        elements:
          -
            fieldUid: cd9c9002-d961-4cfa-8da7-3e45c4a12f7f # Team Members
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: m_team_grid
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Team Grid'
sortOrder: 25
topLevel: true
