childBlocks: null
field: 0721a0d7-c94f-4d51-8847-28aaaf18b31c # News Page Content
fieldLayouts:
  ddbe0df8-5ca6-458d-b76d-22bb0fd55cbe:
    tabs:
      -
        elements:
          -
            fieldUid: d6055877-27dd-431d-b5ea-a58c66494c48 # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b56d8dc7-a81a-4d45-b918-ddacc1675bcc # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 54c7446b-ba5e-4499-85f6-9e661a1087f1 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 47b7e378-7822-4a43-b757-c1e4b1de2996 # ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b60e08fb-c652-49f7-8ef6-2e667ea37e59 # Flush
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9043c2c8-5387-4d20-b2f1-11b854cddb69 # Image Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 2
handle: twoColumnWithImage
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Two Column with Image'
sortOrder: 4
topLevel: true
