contentColumnType: string
fieldGroup: c7c37252-7715-4730-af7f-51d0ef0c84a6 # Common
handle: backgroundColor
instructions: ''
name: 'Background Color'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - White
        -
          - value
          - bg-white
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Black
        -
          - value
          - bg-black
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Dark - Grey'
        -
          - value
          - bg-gray-500
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Medium - Grey'
        -
          - value
          - bg-gray-400
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Light - Grey'
        -
          - value
          - bg-gray-300
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Dark - Red'
        -
          - value
          - bg-red-500
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Medium - Red'
        -
          - value
          - bg-red-400
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Light - Red'
        -
          - value
          - bg-red-300
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Pink
        -
          - value
          - bg-pink-400
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
