contentColumnType: string
fieldGroup: 90f82f48-2e60-488d-96f9-2ca920b7d6f4 # Components
handle: c_buttons
instructions: ''
name: Buttons
searchable: false
settings:
  contentTable: '{{%matrixcontent_c_buttons}}'
  maxBlocks: '3'
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
