contentColumnType: string
fieldGroup: 47dccfeb-fe85-41ac-b747-a53c584bd9a9 # Modules
handle: component_width
instructions: 'Must add up to 1 whole, this is only functional on two column sections'
name: Width
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - 1/2
        -
          - value
          - 1/2
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 1/3
        -
          - value
          - 1/3
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2/3
        -
          - value
          - 2/3
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
