contentColumnType: boolean
fieldGroup: 90f82f48-2e60-488d-96f9-2ca920b7d6f4 # Components
handle: flush
instructions: ''
name: Flush
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
