contentColumnType: string
fieldGroup: 47dccfeb-fe85-41ac-b747-a53c584bd9a9 # Modules
handle: height
instructions: ''
name: Height
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Full
        -
          - value
          - h-full
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Three Quarters'
        -
          - value
          - h-3/4
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Half
        -
          - value
          - h-1/2
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
