columnSuffix: null
contentColumnType: string(7)
fieldGroup: c7c37252-7715-4730-af7f-51d0ef0c84a6 # Common
handle: hexCode
instructions: ''
name: 'Hex Code'
searchable: false
settings:
  defaultColor: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
