contentColumnType: string
fieldGroup: fe24ebf6-cdf5-4307-a008-cd64fd0d33b8 # Globals
handle: navigation
instructions: ''
name: Navigation
searchable: false
settings:
  contentTable: '{{%matrixcontent_navigation}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
