contentColumnType: string
fieldGroup: 47dccfeb-fe85-41ac-b747-a53c584bd9a9 # Modules
handle: teamMembers
instructions: ''
name: 'Team Members'
searchable: false
settings:
  style: tip
  tip: 'This grid will pull all entries from the Team sections'
translationKeyFormat: null
translationMethod: none
type: carlcs\uielementfields\fields\UiTip
