columnSuffix: null
contentColumnType: string
fieldGroup: 9a4892aa-104a-4b33-a326-4864b7730f6e # News
handle: thumbnail
instructions: ''
name: Thumbnail
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:0d9c3bd5-e4e5-497b-9ace-32b66f7905bd' # Images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:0d9c3bd5-e4e5-497b-9ace-32b66f7905bd' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:0d9c3bd5-e4e5-497b-9ace-32b66f7905bd' # Images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
