contentColumnType: string
fieldGroup: 47dccfeb-fe85-41ac-b747-a53c584bd9a9 # Modules
handle: verticalAlignment
instructions: ''
name: 'Vertical Alignment'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - 'Align Middle'
        -
          - value
          - items-center
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Align Top'
        -
          - value
          - items-start
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
