fieldLayouts:
  c750bf23-f6f0-4d56-9f78-41f987d5ef1b:
    tabs:
      -
        elements:
          -
            fieldUid: 4aa2987a-64ab-4605-adec-de3d6e984f60 # Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eb9ddbe8-59e8-4a76-898e-9f77608f8f28 # Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 58fd94e3-a7f4-43e9-9b15-9ead4bdd88f5 # Facebook
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8da0a5b1-f252-4162-bb8a-4b75827cf980 # LinkedIn
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Contact
        sortOrder: 1
handle: general
name: General
