enableVersioning: true
handle: news
name: 'News Articles'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  90e9762b-b063-4ecd-a13d-b89d892e304c: # Aethon Energy
    enabledByDefault: true
    hasUrls: true
    template: _layout/news/_entry
    uriFormat: 'news/{slug}'
structure:
  maxLevels: null
  uid: da39e049-8d35-47eb-96ce-756622a1d042
type: structure
